# This workflow will build and push a .NET Core application to an Azure Function on every push to the master branch.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_DEPLOY_CREDS with a value of the json result of a new service principal, scoped to the given resource group
# For additional information follow the instructions here https://github.com/Azure/login
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NETCORE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: "Build and Deploy"

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: bfyoc-rating-api  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './published'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'                    # set this to the .NET Core version to use

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore packages
      run: dotnet restore

    - name: Build app
      run: dotnet build --configuration Release --no-restore

    # - name: Test app
    #   run: dotnet test --no-build

    - name: Publish app for deploy
      run: dotnet publish --configuration Release --no-build --output ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

  # deploy:
  #   name: Deploy Web App
  #   runs-on: ubuntu-latest
  #   needs: [build, create]
  #   steps:
  #   - name: Download Build Artifact
  #     uses: actions/download-artifact@v1
  #     with:
  #       name: ${{ env.AZURE_WEBAPP_NAME }}

  #   # Login to AZ CLI
  #   - uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_DEPLOY_CREDS }}
    
  #   # Deploy app
  #   - name: 'Deploy to Azure WebApp'
  #     uses: azure/webapps-deploy@v1
  #     with:
  #      app-name: ${{ env.AZURE_WEBAPP_NAME }}
  #      package: ${{ env.AZURE_WEBAPP_NAME }}

  #   # Logout AZ CLI
  #   - name: logout
  #     run: |
  #       az logout
