trigger: none

resources:
  pipelines:
  - pipeline: build
    source: 'bfyoc-rating-api - BUILD'
  
variables:
  vmImageName: 'vs2017-win2016'
  azureSubscription: 'AZURE-PIPELINES-SPN'

stages:
- template: azure-release-pipelines-stage-template.yml
  parameters:
    stageName: 'CI'
    environment: 'API-CI'
    azureSubscription: ${{ variables.azureSubscription }}
    functionAppName: 'bfyoc-rating-api-ci'
    resourceGroupName: 'bfyoc-rating-api-ci'
    storageAccountName: 'azfunctionsrapici'
    region: 'East US'
    packageName: 'bfyoc-rating-api.zip'
