# This workflow will build and push a .NET Core application to an Azure Function on every push to the master branch.
#
# To configure this workflow:
#
# 1. Set up a secret in your repository named AZURE_DEPLOY_CREDS with a value of the json result of a new service principal, scoped to the given resource group
# For additional information follow the instructions here https://github.com/Azure/login
#
# 2. Change the values for the AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NETCORE_VERSION environment variables  (below).
#
# For more information on GitHub Actions for Azure, refer to https://github.com/Azure/Actions
# For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
name: "Build and Deploy"

on:
  push:
    branches:
      - master

env:
  AZURE_FUNCTIONAPP_NAME: bfyoc-rating-api  # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Source/bfyoc-rating-api' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '3.1.101'                    # set this to the .NET Core version to use
  AZURE_SUBSCRIPTION_ID: 'd8a7fa71-02cd-45ab-abbe-e3071eca1519'
  AZURE_RESOURCE_GROUP: 'bfyoc-rating-api-actions'
  

jobs:
  build:
    name: Build Function App
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build function for deploy
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./published
        popd
    
    - name: Publish Build Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        path: '~/work/bfyoc-rating-api/bfyoc-rating-api/${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/published'
        
    - name: Publish Infrastructure Artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: infrastructure
        path: '~/work/bfyoc-rating-api/bfyoc-rating-api/Infrastructure'
        
  provision:
    name: Provision Infrastructure
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2.0.5
        with:
          name: infrastructure
          
      # Authentication
      # Set up the following secrets in your repository: AZURE_CREDENTIALS
      # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
          
      - name: Create Resource Group
        uses: azure/CLI@v1
        with:
          inlineScript: az group create -l eastus -n ${{ env.AZURE_RESOURCE_GROUP }}
      
      - name: Deploy ARM
        uses: azure/CLI@v1
        with:
          inlineScript: az deployment group create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --mode Incremental --name actionsDeploy --template-file $GITHUB_WORKSPACE/function-app-consumption.json --parameters appName='bfyoc-rating-api-team-5' storageAccountName='azfunctionsbfyocstor'
          
      # Logout AZ CLI
      - name: az logout
        run: |
         az logout
        
  deploy:
    name: Deploy Function App
    runs-on: ubuntu-latest
    needs: [build, provision]
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.AZURE_FUNCTIONAPP_NAME }}

      # Authentication
      # Set up the following secrets in your repository: AZURE_CREDENTIALS
      # For details on usage of secrets, please refer https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS  }}
        
    - name: Deploy Function App
      uses: Azure/functions-action@v1.1.5
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          
    # Logout AZ CLI
    - name: az logout
      run: |
       az logout
